### PR TITLE
Add version for Grid webjar

### PR DESCRIPTION
**Pull request by caalador**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/90)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/90)*

**Comment by SomeoneToIgnore** [comment]
Need to exclude and fix the checkbox at least.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/90#-:-L59CHOZM_6Li1NFuLsM:bzavota)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/90)*

**Comment by SomeoneToIgnore** [comment]
Dependencies fixed, now tests fail.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/90#-:-L59KlBErWOCVZRlf6Wu:bydqru9)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/90)*

**Pull request merged**
