### PR TITLE
Update generated components and add lumo style to demos

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/60)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-L2yzFr0dB-P2qnN7ldI:-L2yzFr0dB-P2qnN7ldJ:b5jr73f) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/c9770f9db49440a5364d1371187d6163bc4d5d62/src/main/java/com/vaadin/flow/component/grid/Grid.java#L100)):*
> ```Java
> @HtmlImport("frontend://bower_components/vaadin-grid/vaadin-grid-column.html")
> @HtmlImport("frontend://bower_components/vaadin-grid/vaadin-grid-sorter.html")
> @HtmlImport("frontend://bower_components/vaadin-checkbox/vaadin-checkbox.html")
> ```

Did you get any answer why this was here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60)*

**Comment by ZheSun88** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 100 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-L2yzFr0dB-P2qnN7ldI:-L2yzdu-WjQEbMktw8WB:bfkpxg9) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/c9770f9db49440a5364d1371187d6163bc4d5d62/src/main/java/com/vaadin/flow/component/grid/Grid.java#L100)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Did you get any answer why this was here?
</blockquote></details>

no.. that is why i just removed..it comes from the first commit to the repo... since grid was in flow...so can we find any trace from there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-:-L2z7rvNfnd2ejxEl0Xj:bnfp4nl)*

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 98 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-L33H9D9n-k_jcWuvs8z:-L33H9D9n-k_jcWuvs9-:bbwnpdj) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/6fea1da04cf2d738d5748312cf60bc2ad0a0ba48/src/main/java/com/vaadin/flow/component/grid/Grid.java#L98)):*
> ```Java
> @Tag("vaadin-grid")
> @HtmlImport("frontend://bower_components/vaadin-grid/src/vaadin-grid.html")
> @HtmlImport("frontend://bower_components/vaadin-grid/vaadin-grid-column.html")
> ```

There two things (vaadin-grid-column and vaadin-grid-sorter) are present in `src` directory also, should we use those instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60)*

**Comment by pekam** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 98 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-L33H9D9n-k_jcWuvs8z:-L33JsRL6JImUBOWieOD:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/6fea1da04cf2d738d5748312cf60bc2ad0a0ba48/src/main/java/com/vaadin/flow/component/grid/Grid.java#L98)):*
<details><summary><i>Previously, SomeoneToIgnore (Kirill Bulatov) wrote…</i></summary><blockquote>

There two things (vaadin-grid-column and vaadin-grid-sorter) are present in `src` directory also, should we use those instead?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/60#-:-L33K01ANPiGsuqEQ5rE:bnfp4nl)*

**Pull request merged**
