### PR TITLE
Add extended context menu opened change listener.

### PR DESCRIPTION
**Pull request by rsivan**
The extended method is: addGridContextMenuOpenedChangeListener(ComponentEventListener<GridContextMenuOpenedChangeEvent<T>> listener) which uses the new class GridContextMenuOpenedChangeEvent. Due to minor argument differences Java will not allow this method to formally extend addOpenedChangeListener, thus the added method with a different name and signature. Also enhanced demo to showcase the new feature.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/504)

### CODE REVIEW

**Comment by rsivan** [comment]
1. Notice that I expanded on the original enhancement: in addition to context menu open listener changes, also added a change which allows hiding the selection column in multi-select grids.
2. Added IT for the original change as well as for the additional one.

**Comment by rsivan** [comment]
Sorry for the confusion about two unrelated features. Reverting all changes unrelated to the original feature.

**Comment by rsivan** [comment]
Hello Denis,
Thank you for taking the time to review my contribution.
As this is my first contribution on this forum, can you please summarize for me what should be my next actions, if any?

  Thanks

**Comment by denis-anisimov** [comment]
> Hello Denis,
> Thank you for taking the time to review my contribution.
> As this is my first contribution on this forum, can you please summarize for me what should be my next actions, if any?
> 
> Thanks

Thank you for your contribution.
Nothing is needed from you anymore.
I merge it.

**Comment by rsivan** [comment]
Thanks.

**Pull request merged**
