### PR TITLE
Allow disabling opening item details by clicking on rows

### PR DESCRIPTION
**Pull request by pekam**
Add getter and setter for `detailsVisibleOnClick`, which has a default value of `true`. The demo for details row is separated to it's own tab and there are now two demos: the first one demonstrates only the default functionality with details opening by clicking on rows, and the second one disables this and opens details with the server-side API. Also, changed mentions of "details row" to "item details" in the demo, since this is the API naming we're using.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/53)

### CODE REVIEW

**Comment by pekam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1qtBrHTYvIZxyeH4Ac:-L1qtBrHTYvIZxyeH4Ad:b-2xxpys) (no related file):*
Still need to write tests, but I'm waiting for feedback on the feature and demos first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by ahie** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1397 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1quICgZsn1g3k21iTW:-L1quICgZsn1g3k21iTX:b-jrs0e2) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/11cec4d915922e16aa6da6be5b207e5388ff9874/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1397)):*
> ```Java
>      * @see #setItemDetailsRenderer(TemplateRenderer)
>      */
>     public void setDetailsVisibleOnClick(boolean detailsVisibleOnClick) {
> ```

Could be no-op if `this.detailsVisibleOnClick == detailsVisibleOnClick`?

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 618 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1qtz7EEkKIfJjE8O3k:-L1qtz7EEkKIfJjE8O3l:bpbsw0m) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/11cec4d915922e16aa6da6be5b207e5388ff9874/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L618)):*
> ```Java
>     }
> 
>     private void createItemDetailsOpenedProgrammatically() {
> ```

Could this demo be changed so that a column with a `ButtonRenderer` is added that triggers the details open on-click?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by ahie** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by pekam** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1397 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1quICgZsn1g3k21iTW:-L1qvydYxpejhrpJdqzI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/11cec4d915922e16aa6da6be5b207e5388ff9874/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1397)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could be no-op if `this.detailsVisibleOnClick == detailsVisibleOnClick`?
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 618 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1qtz7EEkKIfJjE8O3k:-L1qvz2RXQX-qi-h_Bej:b-ew8tiw) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/11cec4d915922e16aa6da6be5b207e5388ff9874/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L618)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Could this demo be changed so that a column with a `ButtonRenderer` is added that triggers the details open on-click?
</blockquote></details>

I thought it would be too similar to the default behavior (opening by clicking on rows), but now that I think about it, it makes sense to demonstrate that since it's a common use-case and it shows the server-side API anyway... So I'll start working on that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by pekam** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 618 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-L1qtz7EEkKIfJjE8O3k:-L1r-FoBvvD_k9Rql9z7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/11cec4d915922e16aa6da6be5b207e5388ff9874/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L618)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

I thought it would be too similar to the default behavior (opening by clicking on rows), but now that I think about it, it makes sense to demonstrate that since it's a common use-case and it shows the server-side API anyway... So I'll start working on that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by ahie** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/53#-:-L1uqvOa2pD96TA71nX0:bnfp4nl)*

**Pull request merged**
