### PR TITLE
Update selection models to work with simplified HasValue

### PR DESCRIPTION
**Pull request by Legioth**
Makes things compile again after vaadin/flow#4003

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168#-:-LAx23wf8rhkDYr1WbnG:bnfp4nl)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168#-LAx91gnCwz9BtH_13wG:-LAx91go4-0lXcSA1QN1:b-twvu2v) (no related file):*
The header/footer rows patch changed a lot of stuff inside Grid, this will need to be rebased.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168#-LAx91gnCwz9BtH_13wG:-LB1B9hs2w3dTes10Ay8:b-jquc02) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The header/footer rows patch changed a lot of stuff inside Grid, this will need to be rebased.
</blockquote></details>

There are no merge conflicts, but this patch won't compile until vaadin/flow#4003 has been merged and CheckBox and TextField have been updated to use new generated components (and maybe also recompiled against a Flow after merging vaadin/flow#4003).

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/168#-:-LBLXQYz9K5stXuMNKfv:bnfp4nl)*

**Pull request merged**
