### PR TITLE
Hide the Grid(int) constructor

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
The constructor is made private until https://github.com/vaadin/vaadin-grid-flow/issues/68 is fixed. The related test was disabled. The default pageSize (50) will be used always.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/69)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69#-L3c4-naV96w1qsQ63K8:-L3c4-nbGdzrBzYExS3x:b4eo41v) (no related file):*
Should the test view and IT test just be deleted and added to the 68 ticket so that they can be taken from there?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69#-L3c4-naV96w1qsQ63K8:-L3c5Kx4KCeviubT3u1p:bgs6bw3) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Should the test view and IT test just be deleted and added to the 68 ticket so that they can be taken from there?
</blockquote></details>

Sure, will do that. The test is really superficial though, a proper one would be needed when/if the bug is fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69#-L3c4-naV96w1qsQ63K8:-L3cDdwOB_FPJAxPOzZO:bsq2341) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Sure, will do that. The test is really superficial though, a proper one would be needed when/if the bug is fixed.
</blockquote></details>

Done. Comment added: https://github.com/vaadin/vaadin-grid-flow/issues/68

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69)*

**Comment by caalador** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/69)*

**Pull request merged**
