### PR TITLE
Make Grid add columns based on bean properties

### PR DESCRIPTION
**Pull request by pekam**
Implemented the so-called BeanGrid feature: Added a constructor for Grid that takes a bean-type as it's parameter and automatically adds columns for each of the bean's properties. Also added addColumn(String) method for easily creating columns for sub-properties.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/38)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-palojYAjk36QS5Doh:-L-palojYAjk36QS5Doi:bm8miyk) (no related file):*
Did you consider making this feature available not just though the constructor? I'm wondering about Grids injected via `@Id` - it would be nice to still be able to set columns based on a bean type after the Grid has been constructed.

Ping @pleku about this.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 988 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pW3d7Lj4HZYhLRiN8:-L-pW3d7Lj4HZYhLRiN9:baqg2yz) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/main/java/com/vaadin/ui/grid/Grid.java#L988)):*
> ```Java
>             return addColumn(property);
>         } catch (NoSuchElementException exception) {
>             throw new IllegalArgumentException("Can't resolve property name "
> ```

I suggest adding `'` escaping the arguments of the message, just to show something if the user sends an empty String, for instance.

```
throw new IllegalArgumentException("Can't resolve property name '" + propertyName + "' from '" + propertySet + "'");
```

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pZZA4MR_Eqcq279cR:-L-pZZA4MR_Eqcq279cS:bknfv2c) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L25)):*
> ```Java
> import com.vaadin.ui.grid.Grid.Column;
> 
> public class BeanGridTest {
> ```

I suggest also adding a test with a bean that contains a Collection as one of the attributes. And one array.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pXGigKToct_FovE26:-L-pXGigKToct_FovE27:b-oe49u6) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L57)):*
> ```Java
>     }
> 
>     @Test(expected = IllegalArgumentException.class)
> ```

To make this (and all the exception-based tests) more robust and future-proof, I suggest using  the `ExpectedException` rule. A good description of it can be found here: https://stackoverflow.com/questions/785618/in-java-how-can-i-validate-a-thrown-exception-with-junit

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-palojYAjk36QS5Doh:-L-pd4B8zu43zxmxDug1:bpljp4z) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Did you consider making this feature available not just though the constructor? I'm wondering about Grids injected via `@Id` - it would be nice to still be able to set columns based on a bean type after the Grid has been constructed.

Ping @pleku about this.
</blockquote></details>

I'd split it out to another enhancement issue for now. Please can you create a ticket @pekam ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by pekam** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-palojYAjk36QS5Doh:-L-pr7YeEaUSAWy3BRyg:b-7a98g3) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

I'd split it out to another enhancement issue for now. Please can you create a ticket @pekam ?
</blockquote></details>

Done: https://github.com/vaadin/vaadin-grid-flow/issues/41

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 988 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pW3d7Lj4HZYhLRiN8:-L-pePahh--t7xf0Q3nn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/main/java/com/vaadin/ui/grid/Grid.java#L988)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest adding `'` escaping the arguments of the message, just to show something if the user sends an empty String, for instance.

```
throw new IllegalArgumentException("Can't resolve property name '" + propertyName + "' from '" + propertySet + "'");
```
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pXGigKToct_FovE26:-L-pnkfxv8tcglrD1e06:b1pwd4p) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L57)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

To make this (and all the exception-based tests) more robust and future-proof, I suggest using  the `ExpectedException` rule. A good description of it can be found here: https://stackoverflow.com/questions/785618/in-java-how-can-i-validate-a-thrown-exception-with-junit
</blockquote></details>

Done.

Doing this actually allowed me to notice and fix one case where an exception was not caught and rethrown as I expected. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pXGigKToct_FovE26:-L-pvD6FAoqhdAgHO01g:b903kni) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L57)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Done.

Doing this actually allowed me to notice and fix one case where an exception was not caught and rethrown as I expected. :)
</blockquote></details>

Awesome =)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pZZA4MR_Eqcq279cR:-L08s0KeRDOqXvezx_PQ:brtstxd) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L25)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I suggest also adding a test with a bean that contains a Collection as one of the attributes. And one array.
</blockquote></details>

Actually I'm not sure what this should test.
Should we verify that the values are displayed nicely with collections?
The current implementation uses just `String.valueOf` and seems to work nicely for `List<String>`, but not for `String[]`, which displays ugly `[Ljava.lang.String;@2cf9b6d9
`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pZZA4MR_Eqcq279cR:-L09hNFukR9P7LTV3hUd:bqntp4s) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L25)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Actually I'm not sure what this should test.
Should we verify that the values are displayed nicely with collections?
The current implementation uses just `String.valueOf` and seems to work nicely for `List<String>`, but not for `String[]`, which displays ugly `[Ljava.lang.String;@2cf9b6d9
`
</blockquote></details>

The test in this case is to make sure that:

1- we are aware of the use case
2- the code doesn't blow up when you use it (or blow up in a controlled way, with well defined and documented exceptions)
3- any changes in the current behavior will be detected by the test

The actual implementation is up to you to decide. If the expected output is just to show `[Ljava.lang.String;...`, so be it. Other tickets can be created to improve that if needed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by pekam** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-L-pZZA4MR_Eqcq279cR:-L09nv9ttBZFVDeTxO0O:b-majj6a) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/8da3c2b0841207a43f37a6738d7c2898d94f284e/src/test/java/com/vaadin/ui/grid/tests/BeanGridTest.java#L25)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The test in this case is to make sure that:

1- we are aware of the use case
2- the code doesn't blow up when you use it (or blow up in a controlled way, with well defined and documented exceptions)
3- any changes in the current behavior will be detected by the test

The actual implementation is up to you to decide. If the expected output is just to show `[Ljava.lang.String;...`, so be it. Other tickets can be created to improve that if needed.
</blockquote></details>

I added test to check that columns for arrays and lists are also generated with correct keys. But I ignored the final values that are shown in the grid cells since there's no specs about the expected behavior anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/38#-:-L09vnxAHo7LK90k_I4u:bnfp4nl)*

**Pull request merged**
