### PR TITLE
Make setPageSize public.

### PR DESCRIPTION
**Pull request by caalador**
Setting the page size works as expected.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/93)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93#-L5OYDjhrI98vdSKmAxa:-L5OYDjiqjiO0OGmpySh:bij2now) (no related file):*
Is it possible to test it ?
Unit tests, IT tests ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93)*

**Comment by caalador** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93#-L5OYDjhrI98vdSKmAxa:-L5OYeeidxwK5n6X3ivr:b-3kjt5y) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Is it possible to test it ?
Unit tests, IT tests ?
</blockquote></details>

Only one I can come up with would be a view where we set the pageSize and then check that there are items in the grid.
But I guess that doesn't really test the feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93#-L5OYDjhrI98vdSKmAxa:-L5OZ9x_dm3KA1sqUDfM:bg6sqtc) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Only one I can come up with would be a view where we set the pageSize and then check that there are items in the grid.
But I guess that doesn't really test the feature.

</blockquote></details>

The main problem was to set the pageSize after you have the initial load of items. In my tests some time ago it made the Grid a bit crazy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93#-L5OYDjhrI98vdSKmAxa:-L5OaXVjUu6ukKRPWBta:b-3kd7q1) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The main problem was to set the pageSize after you have the initial load of items. In my tests some time ago it made the Grid a bit crazy.
</blockquote></details>

Yeah, well, may be not tests for the page size itself but verification tests that when the page size is called it doesn't break `Grid`.
I also remember some issue with setting page size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/93)*

**Comment by caalador** [comment]
There's a clear issue when changing pageSize after page population with e.g. a button.
Just setting the page size in a constructor creates no problems.

Closing this and await another solution.

**Pull request closed without merging**
