### PR TITLE
Correct single argument "select" method implementation

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #4111

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgorSVC1Ee5Y5_6UOF:-LCgorSVC1Ee5Y5_6UOG:b-uq5oqj) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L27)):*
> ```Java
> 
> public class AbstractGridMultiSelectionModelTest {
> ```

Missing test testing ticket type of selection where using Object and single item.
Also how has GridMultiSelectionModelTest `selectionEvent_newSelection_oldSelection` passed  with `selectItems` for GridMultiSelectionModel
e.g. `selectionModel.selectItems(john);`

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 45 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgoTcB3Fx5Xp4bveGf:-LCgoTcB3Fx5Xp4bveGg:b-ed2h2n) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L45)):*
> ```
> Cleint
> ```
Typo should be `Client`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgorSVC1Ee5Y5_6UOF:-LCgzuIyBsJvt6UbTqlo:b-mq1a0w) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L27)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Missing test testing ticket type of selection where using Object and single item.
Also how has GridMultiSelectionModelTest `selectionEvent_newSelection_oldSelection` passed  with `selectItems` for GridMultiSelectionModel
e.g. `selectionModel.selectItems(john);`
</blockquote></details>

`String` is `Object`.
In which way it should influence on the functionality which is fixed ?
It's about extra call in `select(T)`  call only.
I may add of course test for not `String` case but I don't see how it makes tests better:
in which way a `String` is different from other object ?

The same for `selectItems` method. I haven't changed it at all. Should I extend the tests for the methods in this PR which I have not been modified ?

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 45 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgoTcB3Fx5Xp4bveGf:-LCh0Xrd8ZYLVnsOGVF6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L45)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> Cleint
> ```
Typo should be `Client`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgorSVC1Ee5Y5_6UOF:-LCh7FrEC8iJjog8nM5V:bh83ug1) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`String` is `Object`.
In which way it should influence on the functionality which is fixed ?
It's about extra call in `select(T)`  call only.
I may add of course test for not `String` case but I don't see how it makes tests better:
in which way a `String` is different from other object ?

The same for `selectItems` method. I haven't changed it at all. Should I extend the tests for the methods in this PR which I have not been modified ?
</blockquote></details>

The point was that there was a test that should have tested that the reported problem doesn't exist, but in reality it didn't work.
So there should be a test that actually fails before the fixes and doesn't after. Else this is just moving code around.
Now there is no code that tests the actual reported bug has been fixed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgorSVC1Ee5Y5_6UOF:-LChE4vB-PK-oTjV0L9t:b-vilzcc) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L27)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

_THIS_ test fails without changes in `AbstractGridMultiSelectionModel`.
Why do you think it doesn't fail ?
I've checked that for sure.

And sure, I totally agree with you. But the test already meets the requirement :)
</blockquote></details>

Yes it does fix the problem (even tested the given sample code which should be used for an IT test, but...). 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java, line 27 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193#-LCgorSVC1Ee5Y5_6UOF:-LChHvn248QVKhNdTcDU:bfe29m6) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0df7e1bf914569a5788a7d2d6660e7980d976647/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java#L27)):*
I mean the _unit test_ fails without changes in the code of this PR.

>So there should be a test that actually fails before the fixes and doesn't after. Else this is just moving code around.

This test fails before the fix and doesn't fail after. The only difference is different type used in the ticket report and in the test. But I don't think it's an issue

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/193)*

**Pull request merged**
