### PR TITLE
Provide an IT test to click Vaadin button inside Grid via space

### LINKED ISSUE #122: Can’t click a button inside a column using Space
A `<vaadin-button>` inside a column can’t be clicked with the keyboard <kbd>Space</kbd> when the cell is focused.

This is reproducible in BeverageBuddy “Categories” view.

screen shot 2018-03-15 at 12 15 48

I’m expecting that `<flow-grid-component-renderer>` causes this – `<vaadin-grid>` doesn’t consider nested buttons/focusable elements when triggering the click. Therefore it might be that this needs a fix in the web component and not in the Flow wrapper.

See https://vaadin.com/components/vaadin-grid/html-examples#grid-selection-demos (last example) for reference how it should work.

@platosha can probably answer right away?

### PR DESCRIPTION
**Pull request by denis-anisimov**
IT verification test for #122.
Closes #122.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
This PR which is just IT test is waiting for a fix in Flow: https://github.com/vaadin/flow/pull/4244

**Comment by ZheSun88** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221#-LEU5xWc-FPVLhOC27GP:-LEU5xWc-FPVLhOC27GQ:b3gted9) (no related file):*
i just read the conversation between you and jouni, from the last two messages, is this test still valid? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221#-LEU5xWc-FPVLhOC27GP:-LEUDWgX1c1BGtGlCkfw:b-92of13) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

i just read the conversation between you and jouni, from the last two messages, is this test still valid? 
</blockquote></details>

Yes.
The test is corrected and now it matches the usecase.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221#-LEU5xWc-FPVLhOC27GP:-LEUDbiXAM9VRZ6yaTqg:b-896fix) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes.
The test is corrected and now it matches the usecase.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221#-LEU5xWc-FPVLhOC27GP:-LEUDbss4LYRPFG_TTed:b-usx5t2) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

great. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/221#-:-LEUHu8DBd1dag3nLAEn:bnfp4nl)*

**Pull request merged**
