### PR TITLE
Hidden select column api

### PR DESCRIPTION
**Pull request by rsivan**
This feature was born from a request from my organization's design team.
The team expects multi-selection tables to NOT show the selection column, using instead a context menu or key shortcut which will select and unselect rows programmatically.

The implementation I am asking to merge into Grid Flow adds a simple call to allow developers to hide that column if they so choose.

Note that developers not interested in this feature do not have to do any changes in their current code, as the default after this change is to show the selection column.
See also demo and IT.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/555)

### CODE REVIEW

**Comment by pleku** [comment]
Hi @rsivan and thanks for the contribution! And patience - sorry for the delay in response and inactivity. Apparently there was some unrelated test failures but I've merged the master branch and another build has been started. We'll take this PR into review as soon as we can.

**Comment by rsivan** [comment]
Any progress on this request?
Thanks

**Comment by denis-anisimov** [comment]
> Any progress on this request?
> Thanks

There are many comments for this PR. Please answer/fix them

**Comment by pleku** [comment]
@rsivan please address the changes requested by the reviewer, thanks.

**Comment by pleku** [comment]
Closing PR due to inactivity by author.

Please reopen if seemed important.

**Pull request closed without merging**
