### PR TITLE
Respect null values in the Column::setComparator(ValueProvider) method

### LINKED ISSUE #64: NPE if column sorting value extractor returns null
```java
grid.setComparator(Patient::getDate)
```
Current Grid implementation fails if `Patient::getDate` returns `null`.

I think it's better to assume `null` as the smallest possible value rather than fail the whole application.

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #64

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/125)

### CODE REVIEW

**Comment by pekam** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 437 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-L7yA2Lbidtccz53Kt7E:-L7yA2Lbidtccz53Kt7F:b-6tao8q) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/77b4e548f210b2117ac2ab3dd418e9b5968c89fe/src/main/java/com/vaadin/flow/component/grid/Grid.java#L437)):*
> ```Java
>                     "Key extractor must not be null");
>             setComparator(Comparator.comparing(keyExtractor,
>                     Comparator.nullsFirst(Comparator.naturalOrder())));
> ```

Framework seems to use `nullsLast`: https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Grid.java#L1012
Should we stick with that or is there a reason to order nulls first?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 437 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-L7yA2Lbidtccz53Kt7E:-L7yGr6xgH2ThOm8yMin:b-n41t8x) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/77b4e548f210b2117ac2ab3dd418e9b5968c89fe/src/main/java/com/vaadin/flow/component/grid/Grid.java#L437)):*
I don't know the answer to this question.
Technically I don't care. Whatever.

The ticket says: 
>I think it's better to assume null as the smallest possible value rather than fail the whole application.

Javadoc for `nullFirst`says:

Returns a null-friendly comparator that considers {@code null} to be less than non-null.

Which is consistent with the ticket (and I personally agree with this).

I'm not aware of any other reason is out of the ticket.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 437 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/125#-L7yA2Lbidtccz53Kt7E:-L7yKote95grYu9FPjnC:b2fl55e) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/77b4e548f210b2117ac2ab3dd418e9b5968c89fe/src/main/java/com/vaadin/flow/component/grid/Grid.java#L437)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

I don't know the answer to this question.
Technically I don't care. Whatever.

The ticket says: 
>I think it's better to assume null as the smallest possible value rather than fail the whole application.

Javadoc for `nullFirst`says:

Returns a null-friendly comparator that considers {@code null} to be less than non-null.

Which is consistent with the ticket (and I personally agree with this).

I'm not aware of any other reason is out of the ticket.
</blockquote></details>

Yeah, but the quote from the ticket sounds more like a proposal than a best possible solution.

Anyway, I don't care that much either, so up to you. But consider if it's possible that some user migrating from FW8 to Flow gets unexpected behavior because his `null` values are now ordered first as they were previously left last.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 437 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-L7yA2Lbidtccz53Kt7E:-L7yY5iWJeE0_LlA9Pkw:b-388487) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/77b4e548f210b2117ac2ab3dd418e9b5968c89fe/src/main/java/com/vaadin/flow/component/grid/Grid.java#L437)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Yeah, but the quote from the ticket sounds more like a proposal than a best possible solution.

Anyway, I don't care that much either, so up to you. But consider if it's possible that some user migrating from FW8 to Flow gets unexpected behavior because his `null` values are now ordered first as they were previously left last.
</blockquote></details>

Please maintain consistency with FW8

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 437 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/125#-L7yA2Lbidtccz53Kt7E:-L80uM0_4nt0XTLXzx-3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/77b4e548f210b2117ac2ab3dd418e9b5968c89fe/src/main/java/com/vaadin/flow/component/grid/Grid.java#L437)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Please maintain consistency with FW8
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by denis-anisimov** [comment]
Test fails because of unrelated issue : https://github.com/vaadin/vaadin-grid-flow/issues/127

**Comment by Legioth** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 432 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-L81Iw2-VRphJ8TQUqZi:-L81Iw2-VRphJ8TQUqZj:bkfjmp7) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/9522e891b680aa4c246f1cf17c21689bc605a561/src/main/java/com/vaadin/flow/component/grid/Grid.java#L432)):*
> ```Java
>          * @see Comparator#comparing(java.util.function.Function)
>          */
>         public <V extends Comparable<? super V>> Column<T> setComparator(
> ```

Doesn't this means that this is applied to all user-provided comparators, meaning that there is no way for an application developer to override in which nulls are ordered?

The corresponding logic in FW8 is only used as the default when the application developer hasn't defined any custom comparator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by Legioth** [comment]
*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 432 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-L81Iw2-VRphJ8TQUqZi:-L81JeXbiMxQ7FxGfiqQ:b8pxyku) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/9522e891b680aa4c246f1cf17c21689bc605a561/src/main/java/com/vaadin/flow/component/grid/Grid.java#L432)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Doesn't this means that this is applied to all user-provided comparators, meaning that there is no way for an application developer to override in which nulls are ordered?

The corresponding logic in FW8 is only used as the default when the application developer hasn't defined any custom comparator.
</blockquote></details>

No, I was confusing the `ValueProvider` overload of `setComparator` with the one based on an actual `Comparator`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125)*

**Comment by pekam** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/125#-:-L81S6fpDa15NPLdqhzV:bnfp4nl)*

**Pull request merged**
