### PR TITLE
Return method reference for descending Column::getComparator

### PR DESCRIPTION
**Pull request by heruan**
A small change for a great gain: since method references are traceable via reflection, persistence frameworks can obtain from them the original comparator (which may be a custom implementation) set on a column if Grid/Column use only method references to make them serializable.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/21)

### CODE REVIEW

**Comment by heruan** [comment]
See also https://github.com/vaadin/flow/issues/2991.

**Comment by heruan** [comment]
Still, `Grid::createSortingComparator` uses `(x, y) -> 0` as identity for reduction, and this breaks the traceability of the original comparators. Also, this would issue an unnecessary sorting if `sortOrder` is empty.

Why not return an `Optional`, reducing without the identity?

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/21)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/21)*

**Pull request merged**
