### PR TITLE
Fix Grid state when reattaching it to the tree

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This fix uses the refactored beforeClientResponse mechanism in Flow. Depends on https://github.com/vaadin/flow/pull/3617

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/105)

### CODE REVIEW

**Comment by Legioth** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mh14cbd0cC0X2_rZn:-L6Mh14cbd0cC0X2_rZo:b9iey3z) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L772)):*
> ```Java
>                 SelectionMode.SINGLE);
> 
>         getElement().addAttachListener(event -> getElement().getNode()
> ```

There's a shorter way of doing this: simply override `Component.onAttach`.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 777 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mgs1JoKtVZi6NIjqY:-L6Mgs1JoKtVZi6NIjqZ:b-7er5a6) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L777)):*
> ```Java
> 
>     private void initConnector(UI ui) {
>         ui.getPage().executeJavaScript("window.gridConnector.initLazy($0)",
> ```

Doesn't this mean that we're running `initLazy` multiple times if Grid is attached and detached multiple times during the same round trip?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, line 332 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Q4ixqe48OdIVBw6dU:-L6Q4ixqe48OdIVBw6dV:b-pvth79) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java#L332)):*
> doClientSideDesselection

`doClientSideDesselection` -> `doClientSideDeselection` ?

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mh14cbd0cC0X2_rZn:-L6Q5-vsMAkMFaTlwxJp:b8ubxiw) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L772)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

There's a shorter way of doing this: simply override `Component.onAttach`.
</blockquote></details>

`Component.onAttach` may be overwritten by the developer without calling `super`.
So may be this way is safer.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 777 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mgs1JoKtVZi6NIjqY:-L6Q5MWy1VCWzqGf5J-r:bnxx8ed) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L777)):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Doesn't this mean that we're running `initLazy` multiple times if Grid is attached and detached multiple times during the same round trip?
</blockquote></details>

It does.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Q5cGNviEL_ggmy7lT:-L6Q5cGNviEL_ggmy7lU:b6qmo2r) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1250)):*
> getElement().callFunction("$connector." + function, values);

Does it work? 
`callFunction` calls the function for element (`getElement()`) . Here you are calling the function for `$connector` not for the element....
Or `$connector.function` is the name of the function ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Q5cGNviEL_ggmy7lT:-L6QLZmGBOOlHpnC7CHp:b-7g2707) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1250)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> getElement().callFunction("$connector." + function, values);

Does it work? 
`callFunction` calls the function for element (`getElement()`) . Here you are calling the function for `$connector` not for the element....
Or `$connector.function` is the name of the function ?
</blockquote></details>

Exactly, `$connector` is an attribute of the Grid (created by the `initLazy`), and the function is `$connector.function`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java, line 332 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Q4ixqe48OdIVBw6dU:-L6RdzjmNfam27hrEy2u:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java#L332)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> doClientSideDesselection

`doClientSideDesselection` -> `doClientSideDeselection` ?
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 772 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mh14cbd0cC0X2_rZn:-L6RRwDcnisFGU8lpw5r:b1eua8u) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L772)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`Component.onAttach` may be overwritten by the developer without calling `super`.
So may be this way is safer.
</blockquote></details>

We never override the `onAttach` in any component.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 777 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6Mgs1JoKtVZi6NIjqY:-L6RRqPqapB-VssmASxW:b-p4ybu) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/3ee9523ede116d29a5749dca0896388965406233/src/main/java/com/vaadin/flow/component/grid/Grid.java#L777)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

It does.
</blockquote></details>

Oops, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 790 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6VQQbhEbR6MoE1d36j:-L6VQQbhEbR6MoE1d36k:bf2t8wo) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0fe5812360f2b31debcba07b844bd9a996e44eb6/src/main/java/com/vaadin/flow/component/grid/Grid.java#L790)):*
>   private void initConnector(UI ui) {
>         ui.getPage().executeJavaScript("window.gridConnector.initLazy($0)",
>                 getElement());
>     }

Wasn't it fixed? (the same issue as in the list box?).
Shouldn't you call 

`getElement().getNode().runWhenAttached( ui-> ui.beforeClientResponse(this,...` in the CTOR instead of 
`getElement().getNode().runWhenAttached(this::initConnector);`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 790 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105#-L6VQQbhEbR6MoE1d36j:-L6VRqianxsnvELNBAgT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/0fe5812360f2b31debcba07b844bd9a996e44eb6/src/main/java/com/vaadin/flow/component/grid/Grid.java#L790)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>   private void initConnector(UI ui) {
>         ui.getPage().executeJavaScript("window.gridConnector.initLazy($0)",
>                 getElement());
>     }

Wasn't it fixed? (the same issue as in the list box?).
Shouldn't you call 

`getElement().getNode().runWhenAttached( ui-> ui.beforeClientResponse(this,...` in the CTOR instead of 
`getElement().getNode().runWhenAttached(this::initConnector);`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/105)*

**Pull request merged**
