### PR TITLE
Port the MultiSelect API from FW8, and update demo

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Also add a safeguard on GridViewIT to make the ComponentRenderer tests more reliable on CI.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/156)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 734 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156#-LAIv78Q5wu-iH49k75p:-LAIv78Q5wu-iH49k75q:b2jdgjt) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/84ebfce4db45b0a081331e789fce70eb1888d8ec/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L734)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         try {
>             /*
>              * Wait a bit for the changes to propagate from the server to the
>              * client. Without this wait, some elements can be stale when this
>              * method is executed, causing instability on the tests.
>              */
>             Thread.sleep(1000);
>         } catch (Exception e) {
>         }
> ```
</details>


Can this be replaced with `waitUntil` with some condition ?

Also in case of preserving the code: don't catch an `Exception`. It should be narrow type.
And may be either declare the method as `throws` or rethrow `RuntimeException` .
Don't catch it silently.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156)*

**Comment by gilberto-torrezan** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 734 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156#-LAIv78Q5wu-iH49k75p:-LAMcFqt6YysREESjD0L:b-izskuy) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/84ebfce4db45b0a081331e789fce70eb1888d8ec/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L734)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         try {
>             /*
>              * Wait a bit for the changes to propagate from the server to the
>              * client. Without this wait, some elements can be stale when this
>              * method is executed, causing instability on the tests.
>              */
>             Thread.sleep(1000);
>         } catch (Exception e) {
>         }
> ```

Can this be replaced with `waitUntil` with some condition ?

Also in case of preserving the code: don't catch an `Exception`. It should be narrow type.
And may be either declare the method as `throws` or rethrow `RuntimeException` .
Don't catch it silently.
</blockquote></details>

I tried to find a good `waitUntil` candidate (and even improved the one below), but failed miserably. The way the ComponentRenderer renders the content makes everything in terms of testing really complicated. So to avoid the endless chain of broken build I put this sleep directly.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 734 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156#-LAIv78Q5wu-iH49k75p:-LAMgKqkEBT11q_rvM9X:b5ej7uv) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/84ebfce4db45b0a081331e789fce70eb1888d8ec/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L734)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I tried to find a good `waitUntil` candidate (and even improved the one below), but failed miserably. The way the ComponentRenderer renders the content makes everything in terms of testing really complicated. So to avoid the endless chain of broken build I put this sleep directly.
</blockquote></details>

The problem is that `1000` may work for you locally but may fail on validation on TC or for someone else locally.....

But OK.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/156#-:-LAMg_ymCRw5GG4PxNgu:bnfp4nl)*

**Pull request merged**
