### PR TITLE
Add support for disabled Grid

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Disabled Grids don't allow selection, expand/collapse of details rows and all input/selection elements inside it are disabled (they don't fire events to the server). But scrolling through the items still work.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/148)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148#-L9suNif0phqjtEnYWwa:-L9suNif0phqjtEnYWwb:b-hbmp9z) (no related file):*
This PR is still using the `onEnabledStateChange` instead of `onEnabledStateChanged`, so if it gets merged before the renaming, a new PR will need to be made.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148)*

**Comment by denis-anisimov** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1804 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148#-L9sxtoK0UCKMmw-Qs8K:-L9sxtoLBmnqoYeEk41m:bxkbpjr) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/13301ddb7c7b6384833a0a2aed70181d56302d01/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1804)):*
> ```
> getDataCommunicator().reset();
> ```

I'm pretty sure there is a reason for this but it's absolutely unclear why.
Please add a comment. 

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 71 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148#-L9sy62C5r-YpF0DShWk:-L9sy62C5r-YpF0DShWl:bblduc6) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/13301ddb7c7b6384833a0a2aed70181d56302d01/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L71)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     public static List<Person> items = new ArrayList<>();
>  
>     static {
>         items = createItems();
>     }
>     public static class PersonComponent extends Div {   ⋯ expand 45 lines
> ```
</details>


Not related to this PR but WHY ?
Why not just assign `items` immediately on declaration ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148)*

**Comment by gilberto-torrezan** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1804 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148#-L9sxtoK0UCKMmw-Qs8K:-L9sz_Cv9e9to2R8uhg1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/13301ddb7c7b6384833a0a2aed70181d56302d01/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1804)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> getDataCommunicator().reset();
> ```

I'm pretty sure there is a reason for this but it's absolutely unclear why.
Please add a comment. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid-flow/148#-:-L9t08hx1fH-tfKYSurx:bnfp4nl)*

**Pull request merged**
