### PR TITLE
Try to compare result of value provider based on the common type

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #139

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Prerequisite: vaadin/flow#3986

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 868 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164#-LAvl_XB7X3sKmu6XbSY:-LAvl_XB7X3sKmu6XbSZ:bi24zo) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/9bb0b665d150799d2b34ef4987e2d2ae51d577a9/src/main/java/com/vaadin/flow/component/grid/Grid.java#L868)):*
> ```Java
>                 .<T> of("[[item." + columnId + "]]").withProperty(columnId,
>                         value -> String.valueOf(valueProvider.apply(value))));
>         column.setComparator((a, b) -> compareMaybeComparables(
> ```

This will make all Columns created by this method sortable by default, which then will show the sorting indicator. I suggest changing how the `setSortable` behaves, or make this method call `setSortable(false)` after setting the comparator.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 868 at r2](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164#-LAvl_XB7X3sKmu6XbSY:-LAvp2fOBbH-muYNGl8j:b-yec4t8) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/9bb0b665d150799d2b34ef4987e2d2ae51d577a9/src/main/java/com/vaadin/flow/component/grid/Grid.java#L868)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This will make all Columns created by this method sortable by default, which then will show the sorting indicator. I suggest changing how the `setSortable` behaves, or make this method call `setSortable(false)` after setting the comparator.
</blockquote></details>

Oh nice, `setComparator` mutates two states.
OK.
Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/164#-:-LAvqTqr3C8P-H7HVgMk:bnfp4nl)*

**Pull request merged**
