### PR TITLE
Add removeColumn and removeColumnByKey methods to Grid.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Also add tests and change the BeanGrid demo to remove columns instead of just hiding them.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/54)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qzLioXi0DDwCQWbHw:-L1qzLioXi0DDwCQWbHx:b-havdy3) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L259)):*
> extraGenerator

This is always null?

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1428 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qxmGaKXHcS0dqEV2H:-L1qxmGbqYC5iJWZO9o2:bk7yzi5) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1428)):*
> Removing <code>null</code> is a NO-OP.

Feels inconsistent with other APIs (that is, most of them throw on null).

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1443 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qz5xmuo3PGYhpgd4k:-L1qz5xmuo3PGYhpgd4l:bul31rq) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1443)):*
> getElement().removeChild(column.getElement());

Will this work with merged columns?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54)*

**Comment by gilberto-torrezan** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1443 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qz5xmuo3PGYhpgd4k:-L1r-EP5qTKuiOdvk-dZ:b1478zw) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1443)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> getElement().removeChild(column.getElement());

Will this work with merged columns?
</blockquote></details>

Damn, it won't. I totally forgot about it. I'll change it and add tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qzLioXi0DDwCQWbHw:-L1r1-JW1P9-sP3UcovR:bvpeo2n) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L259)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> extraGenerator

This is always null?
</blockquote></details>

Removed. Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1428 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qxmGaKXHcS0dqEV2H:-L1r11jucZ3UlY57c5Qk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1428)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> Removing <code>null</code> is a NO-OP.

Feels inconsistent with other APIs (that is, most of them throw on null).
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1443 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-L1qz5xmuo3PGYhpgd4k:-L1rBVcgqH5kyANTDLFg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/ac0c77e481318ae001e3e43a23806f917b530ad3/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1443)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Damn, it won't. I totally forgot about it. I'll change it and add tests.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54)*

**Comment by ahie** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/54#-:-L1rF7yZFitGkQ1QPvdD:bnfp4nl)*

**Pull request merged**
