### PR TITLE
Make ComponentRenderers use virtual children

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This patch requires the changes made in Flow for the same feature. See https://github.com/vaadin/flow/pull/3116.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/40)

### CODE REVIEW

**Comment by ahie** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q9Dk7nO3SEBa6CxIv:-L-q9Dk7nO3SEBa6CxIw:bmqjntm) (no related file):*
Rerunning the validation build. Looks like it was run against an older version of flow.

---

*[src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q9X5_7Kvi7MDOpUQ-:-L-q9X5_7Kvi7MDOpUQ0:bdjp8q6) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/bdd07e368b5ba008017f52e773d67db3d9103e29/src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java#L48)):*
> ComponentDataGenerator

Seems like a weird place to have this class. Would probably make more sense nested inside `Grid`, but that class is already so bloated.

---

*[src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q8OPhoBvFpdDKgUWh:-L-q8OPhoBvFpdDKgUWi:bo1vhoe) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/bdd07e368b5ba008017f52e773d67db3d9103e29/src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html#L6)):*
> _notifyResize(){

Sorry, didn't notice this in the flow PR. Just a minor nit: at least the polymer build tool complains if you override private methods, so this could actually be public. Not worth blocking this PR though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q9Dk7nO3SEBa6CxIv:-L-qAtZscMkAnDQifOKY:bbzi0vz) (no related file):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Rerunning the validation build. Looks like it was run against an older version of flow.
</blockquote></details>

That's one downside of having different modules for the components =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40)*

**Comment by gilberto-torrezan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q9X5_7Kvi7MDOpUQ-:-L-qB4tAvkyLcxfBDSo7:bcg9uci) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/bdd07e368b5ba008017f52e773d67db3d9103e29/src/main/java/com/vaadin/ui/grid/GridTemplateRendererUtil.java#L48)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> ComponentDataGenerator

Seems like a weird place to have this class. Would probably make more sense nested inside `Grid`, but that class is already so bloated.
</blockquote></details>

That's why I moved away from it. This class has everything related to Templates and Component Renderers, so it's easier to find the logic than mixed with other Grid stuff.

---

*[src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html, line 6 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q8OPhoBvFpdDKgUWh:-L-qBXVYuK67pf9kzAD5:bydga09) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/bdd07e368b5ba008017f52e773d67db3d9103e29/src/main/resources/META-INF/resources/frontend/flow-grid-component-renderer.html#L6)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> _notifyResize(){

Sorry, didn't notice this in the flow PR. Just a minor nit: at least the polymer build tool complains if you override private methods, so this could actually be public. Not worth blocking this PR though.
</blockquote></details>

My kingdom for a `protected` keyword in JS.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40)*

**Comment by ahie** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40#-L-q9Dk7nO3SEBa6CxIv:-L03e9AlW7MLrwF52ykw:bnfp4nl) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That's one downside of having different modules for the components =/
</blockquote></details>

:lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/40)*

**Pull request merged**
