### PR TITLE
Grid data view tests supplement

### PR DESCRIPTION
**Pull request by mshabarov**
Generic data view unit test is moved to Flow, data view IT tests is supplemented with add/remove/update cases.
Depends on https://github.com/vaadin/flow/pull/8639

### CODE REVIEW

**Comment by caalador** [comment]
Needs conflict resolution.

**Comment by caalador** [comment]
Is this PR still valid as trying to merge master into the branch generates a conflic that is not GridDataViewImplTest also master doesn't contain this file anymore as it was renamed in `Add getItem(int index) to DataView #8652`.

**Comment by mshabarov** [comment]
Oh, I see. Thanks! This PR needs some rework. Will do

**Comment by mshabarov** [comment]
Pending `master-to-4.0` cherry pick merging, as it contains the necessary fixes in abstract test on flow side https://github.com/vaadin/flow/pull/8845.

**Comment by caalador** [comment]
For some reason it now fails: GridDataViewTest.dataViewWithItems_getItem_returnsCorrectItem
Which should only get the items 0, 1, 2 without any changes and in the middle slot it for some reason gets first.

**Review by caalador — APPROVED** [review]

**Pull request merged**
