### PR TITLE
Fix for #366

### PR DESCRIPTION
**Pull request by stefanuebe**
Issue fix for #366 

The `gridConnector` now adds listeners to the grid for `mouseup`, `mousedown` and `contextmenu` events. 

The `contextmenu` and the `mouseup` event lead finally to `_fireClickEventOnOtherMouseButtons` which simulates partially the normal click handling, without activating the item or selecting it. Also depending on set properties, the default browser actions are prevented (see details below).

The `mousedown` event is needed for the special case of preventing the browser default action of the middle key (mostly scrolling). 

All events lead to the `ItemClickEvent` in Java and allow usage of `event.getButton()`. 

Also the grid now provides a method `preventDefaultMouseClickActions(boolean)`, so that the dev can decide to prevent the default actions, that inflict on middle our right mouse button. (This method is independent from the click listener).

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/818)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Would this fire a row click event on Android if you press a row long enough to create a "contextmenu" event? This would be unexpected as it's not a click and it might behave differently on iOS.

**Comment by stefanuebe** [comment]
Tested the long touch on a Surface Book Windows Chrome, Firefox and Edge and on Android  Chrome. In all cases the long click only fired the `contextmenu` event, not the normal click event. 

Firefox and Edge send `button 2` with the mouse event. Chrome sends `button 0` (Windows and Chrome), which is a problem, since that indicates on the server side, that the user clicked "normally" on the item. 

Question is, if we want to modify the mouse event in the case of Chrome and set the `button` manually to `2`?

**Comment by stefanuebe** [comment]
Added above described special case handling

**Comment by tomivirkki** [comment]
> In all cases the long click only fired the contextmenu event, not the normal click event

What I meant is that a listener added with addItemClickListener shouldn't invoke on row long press on touch devices because it's not a click and it doesn't work consistently across browsers (iOS Safari). On desktop, it also might be strange if a _click_ listener is invoked when the "contextmenu" event occurs by "pressing the context menu key" as described here https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event.

**Comment by tomivirkki** [comment]
Closing this. I think the feature needs more design. As discussed, a long touch, which causes a contextmenu-event is not really a click-event. Maybe a dedicated listener for contextmenu -event makes more sense. But in every case, this would count as a new feature.

**Pull request closed without merging**
