### PR TITLE
Move more it tests

### PR DESCRIPTION
**Pull request by ZheSun88**
and add needed dependencies
so far there will be one more test on sorting needed

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/32)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 86 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32#-L-AW8gy6wsTiDnUbtOi:-L-AW8gy6wsTiDnUbtOj:bf98ffa) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/45253c9e7dd9b7d6467ad3b9feca6043bf85a399/pom.xml#L86)):*
> <groupId>org.easymock</groupId>

Is it used anywhere ?
I would recommend to use mockito only.

---

*[src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionModelTest.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32#-L-AWmkiCGNwhyDBaK35:-L-AWmkiCGNwhyDBaK36:b-13fov7) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/45253c9e7dd9b7d6467ad3b9feca6043bf85a399/src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionModelTest.java#L55)):*
> private Capture<List<Person>> currentSelectionCapture;

I guess that's the only reason of using Easy mock.
Please replace `Capture` with `AtomicReference`  and get rid of easymock completely.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32)*

**Comment by ZheSun88** [comment]
Review status: 18 of 20 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 86 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32#-L-AW8gy6wsTiDnUbtOi:-L-Apb9XMUgursPGSwT6:b-hfpv0l) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/45253c9e7dd9b7d6467ad3b9feca6043bf85a399/pom.xml#L86)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> <groupId>org.easymock</groupId>

Is it used anywhere ?
I would recommend to use mockito only.
</blockquote></details>

removed

---

*[src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionModelTest.java, line 55 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32#-L-AWmkiCGNwhyDBaK35:-L-Apct94cB478p4Iejt:b-7rl0jd) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/45253c9e7dd9b7d6467ad3b9feca6043bf85a399/src/test/java/com/vaadin/ui/grid/it/GridMultiSelectionModelTest.java#L55)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> private Capture<List<Person>> currentSelectionCapture;

I guess that's the only reason of using Easy mock.
Please replace `Capture` with `AtomicReference`  and get rid of easymock completely.
</blockquote></details>

done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32)*

**Comment by ZheSun88** [comment]
@denis-anisimov  remember to close this one please

---

Review status: 18 of 20 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32#-:-L-FnmZ11ChV3kOlR1DA:b-m26i5j)*

**Comment by denis-anisimov** [comment]
For some reasons I didn't get email notification with your answers.
But you have conflicts that needs to be resolved manually.

**Comment by ZheSun88** [comment]
@denis-anisimov I have resolved the conflicts

**Comment by denis-anisimov** [comment]
Reviewed 1 of 22 files at r1, 2 of 2 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/32)*

**Pull request merged**
