### PR TITLE
Add API for joining footer cells

### PR DESCRIPTION
**Pull request by pekam**
Now both header and footer cells can be joined on the currently out-most row. If joining is not possible in the current DOM structure, the column groups are moved upwards in the element hierarchy to find a place where the joined cell fits in.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, line 271 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzCc7c0TcZoHD20WqY:-LBzCc7c0TcZoHD20WqZ:b-i35ymb) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java#L271)):*
> ```Java
>      * @return the Column children of this component
>      */
>     protected List<Column<?>> getBottomChildColumns() {
> ```

Can you have `Column` and `ColumnGroup` as direct children at the same time? If yes, then this recursion can return just part of the children.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 195 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzDIjC5fAn1CaABwgc:-LBzDIjC5fAn1CaABwgd:bd22y4a) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L195)):*
> ```Java
>      * <p>
>      * The cells to join must be adjacent cells in this row, and this row must
>      * be the out-most row.
> ```

I don't know which is the most correct, outmost, out-most or outermost.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 216 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzKOwACWFL16aQyVpb:-LBzKOwACWFL16aQyVpc:bchbbln) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L216)):*
> ```Java
>      * @return the merged cell
>      */
>     public CELL join(Collection<CELL> cells) {
> ```

Due to the limitations of the webcomponent structure and how it makes it different from FW8, there should be a topic in the tutorial explaining how the joining works. Please create a ticket about it (if there isn't one already) so we don't forget.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 254 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzHDZ-1ptfHYLNv3m4:-LBzHDZ-1ptfHYLNv3m5:b-xx6nq4) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L254)):*
> ```Java
>                 layers);
> 
>         if (layerInsertIndex == layers.indexOf(layer) + 1) {
> ```

This method is yuuuge...
I recommend splitting it up using two other private methods: one for when the cells can be joined in place, and one for when you have to move the column layer up in the hierarchy.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 364 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzJqSC5_n50p_lWoQr:-LBzJqSC5_n50p_lWoQs:b-kir76x) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L364)):*
> ```Java
>                     .anyMatch(col -> !bottomColumnsToJoin.contains(col));
>             if (otherColumnsJoined) {
>                 throw new IllegalArgumentException(
> ```

This possible error is not mentioned in the javadocs of the `join` methods.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1278 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzL6eqDIe8oJPxNMyT:-LBzL6eqDIe8oJPxNMyU:b-uygn11) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1278)):*
> ```Java
>         if (layer.equals(columnLayers.get(0))) {
>             throw new IllegalArgumentException(
>                     "The bottom column layer should not be removed");
> ```

`should not` -> `cannot` or ` can't`

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1286 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzLXmv-RKd33CUVAC4:-LBzLXmv-RKd33CUVAC5:bb8iave) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1286)):*
> ```Java
>                     column.getElement().getChildren()
>                             .filter(child -> child.getTag()
>                                     .contains("vaadin-grid-column"))
> ```

This is dangerous. Any user can create a component that the tag name is `my-vaadin-grid-column`. I suggest finding the exact children you want to handle here, without `contains`.

The safest way is to find the component of a given column element, and checking the`instanceof`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187)*

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 470 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzQVQ_0T14GjaOoriS:-LBzQVQ_0T14GjaOoriT:bz7gdbv) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L470)):*
> ```Java
> 
>     @Test
>     public void joinCellsOnBothRows_addAndJoinMore() {
> ```

I couldn't understand what `_addAndJoinMore` mean here.

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 617 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzPF9x9ZxKVV_GUmi4:-LBzPF9x9ZxKVV_GUmi5:bidi9iz) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L617)):*
> ```Java
>         grid.removeColumn(secondColumn);
>         Assert.assertEquals(
>                 "The joined header cell should remain when only one of the child columns is removed",
> ```

`child columns` -> `children columns`. Courtesy of the grammar police. =P

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 635 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzOubCELizeKkqXCMm:-LBzOubCELizeKkqXCMn:b76hbml) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L635)):*
> ```Java
>         IntStream.range(0, rows.length).forEach(i -> {
>             Assert.assertSame(
>                     "Grid did no return expected header rows in order from top to bottom",
> ```

`did no` -> `did not` or `didn't`

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 645 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzOzBL-NBZjaXkza-w:-LBzOzBL-NBZjaXkza-x:b76hbml) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L645)):*
> ```Java
>         IntStream.range(0, rows.length).forEach(i -> {
>             Assert.assertSame(
>                     "Grid did no return expected footer rows in order from top to bottom",
> ```

`did no` -> `did not` or `didn't`

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java, line 270 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzR9aI0otnK9qlTq8Z:-LBzR9aI0otnK9qlTq8_:bn24l9y) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java#L270)):*
> ```Java
>         assertFooterOrder(8, 9, 10, 11, 12, 13, 14, 15);
> 
>         clickButton("join-headers-01");
> ```

Please also add some assertions about the footer order when the header is changed (and vice-versa), since they share the same structure. Just in case.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, line 271 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzCc7c0TcZoHD20WqY:-LBzQXtB9gs1mQO7bZng:bu746o4) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java#L271)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Can you have `Column` and `ColumnGroup` as direct children at the same time? If yes, then this recursion can return just part of the children.
</blockquote></details>

It should not be possible with the `ColumnLayer` structure. But the contract of the method doesn't mention that and expecting that would make this component class unnecessarily depend on the `ColumnLayer` concept...
So done.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 216 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzKOwACWFL16aQyVpb:-LBzYIOKBwqkyMFfgSjl:bg4pdlw) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L216)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Due to the limitations of the webcomponent structure and how it makes it different from FW8, there should be a topic in the tutorial explaining how the joining works. Please create a ticket about it (if there isn't one already) so we don't forget.
</blockquote></details>

I found this ticket and added a comment:
https://github.com/vaadin/flow-and-components-documentation/issues/137

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 254 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzHDZ-1ptfHYLNv3m4:-LBz_Wl5ASDBz8wRep1M:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L254)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This method is yuuuge...
I recommend splitting it up using two other private methods: one for when the cells can be joined in place, and one for when you have to move the column layer up in the hierarchy.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractRow.java, line 364 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzJqSC5_n50p_lWoQr:-LBzVriaE_7cWj4jskBj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/AbstractRow.java#L364)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This possible error is not mentioned in the javadocs of the `join` methods.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1278 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzL6eqDIe8oJPxNMyT:-LBzW-Vc3PJgCP19UhZG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1278)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`should not` -> `cannot` or ` can't`
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 1286 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzLXmv-RKd33CUVAC4:-LBzaLYF9Euh4VjcCxWe:b-eqm5un) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/main/java/com/vaadin/flow/component/grid/Grid.java#L1286)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This is dangerous. Any user can create a component that the tag name is `my-vaadin-grid-column`. I suggest finding the exact children you want to handle here, without `contains`.

The safest way is to find the component of a given column element, and checking the`instanceof`.
</blockquote></details>

Done.
About the class casting: We can expect that the columns are `ColumnGroups` because the method can't be used for the bottom layer.

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 470 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzQVQ_0T14GjaOoriS:-LBzbGkwBtpuC-5_Dyz9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L470)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

I couldn't understand what `_addAndJoinMore` mean here.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 635 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzOubCELizeKkqXCMm:-LBzby9a3qEeBzgAeree:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L635)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`did no` -> `did not` or `didn't`
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java, line 645 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzOzBL-NBZjaXkza-w:-LBzbyZ60Tfa-K03VkM3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/HeaderFooterTest.java#L645)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

`did no` -> `did not` or `didn't`
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java, line 270 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-LBzR9aI0otnK9qlTq8Z:-LBzcGiNAcP_JyX1D_C8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/22c8bf31cfa5133e5b60383b0e85aa2da2bbdc25/src/test/java/com/vaadin/flow/component/grid/it/GridHeaderFooterRowIT.java#L270)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Please also add some assertions about the footer order when the header is changed (and vice-versa), since they share the same structure. Just in case.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/187#-:-LBzeETP2LpG145vSAYc:bnfp4nl)*

**Pull request merged**
