### PR TITLE
Using new webjars

### PR DESCRIPTION
**Pull request by ZheSun88**
renaming repository id;
add logging dependency;
remove HtmlImport in component demo file.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/81)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81#-L4_EB7penM9Fh2QzEEN:-L4_EB7penM9Fh2QzEEO:b5m97lp) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/2e5c8b25a1b220858dd95ac1815644c6cf84a50b/pom.xml#L25)):*
> fvaadin-snapshots

typo ?
`vaadin-snapshots` ?

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81#-L4_EHJW-x8tlz3sLTQP:-L4_EHJW-x8tlz3sLTQQ:bjbl7u2) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/2e5c8b25a1b220858dd95ac1815644c6cf84a50b/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L60)):*
> public class GridView extends DemoView {

No `Lumo` theme via annotation ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pom.xml, line 25 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81#-L4_EB7penM9Fh2QzEEN:-L4_nPgcI7xTsMdongWD:b-vn9g92) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/2e5c8b25a1b220858dd95ac1815644c6cf84a50b/pom.xml#L25)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> fvaadin-snapshots

typo ?
`vaadin-snapshots` ?
</blockquote></details>

oops.. done

---

*[src/test/java/com/vaadin/flow/component/grid/demo/GridView.java, line 60 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81#-L4_EHJW-x8tlz3sLTQP:-L4_nQhLzOACBMamZRU2:b3ffxsh) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/2e5c8b25a1b220858dd95ac1815644c6cf84a50b/src/test/java/com/vaadin/flow/component/grid/demo/GridView.java#L60)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public class GridView extends DemoView {

No `Lumo` theme via annotation ?
</blockquote></details>

no, same as others

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/81)*

**Pull request merged**
