### PR TITLE
Migration to the new renderer structure.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/84)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, line 111 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4nzelKjxbqdgWiTQvA:-L4nzelKjxbqdgWiTQvB:bb94zdn) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java#L111)):*
> Rendering<?> rendering = renderer.render(getElement(), null);
>         rendering.getTemplateElement().get().setAttribute("class", "footer");

This method differs from the method above in `"footer"` attribute value.
Has sense to extract it as a `private` method with additional parameter and delegate.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 541 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o-w1hIT7NpYyinbBY:-L4o-w1hIT7NpYyinbBZ:bktu132) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/main/java/com/vaadin/flow/component/grid/Grid.java#L541)):*
> Rendering<?> rendering = renderer.render(getElement(), null);
>             rendering.getTemplateElement().get().setAttribute("class",
>                     "header");

Why not call `super.setHeader`  instead ?
OK, you need `rendering` instance here.

Then I would suggest to extract original method to another which returns `Rendering` and delegate in the super class to it (if needed at all).
And call this method here as well.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 590 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o0ulkofn5RZvvwBIL:-L4o0ulkofn5RZvvwBIM:b1k0tnv) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L590)):*
> assertCellContent(
>                 "<flow-grid-component-renderer appid=\"ROOT\"><div><label>$$$</label></div></flow-grid-component-renderer>",
>                 cells.get(4));

I strongly object from such exact string comparison.
There are two many hardcoded strings.
It's totally fine if the String content is different. You don't need the exact match. You need only the top level element with the given tag name, _SOME_ attribute values and _SOME_ inner subelements.

I've had hard time once to fixing such comparison because changes in Grid web component (and my PR had no any relation to the test which I have been fixing).

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 599 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o1rzaz02ZEnucThyS:-L4o1rzaz02ZEnucThyT:b-w7gi5s) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L599)):*
> assertCellContent(
>                 "<flow-grid-component-renderer appid=\"ROOT\"><div><label>$</label></div></flow-grid-component-renderer>",
>                 cells.get(10));

Same here.
Please no exact HTML content matches.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84)*

**Comment by gilberto-torrezan** [comment]
Review status: 6 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java, line 111 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4nzelKjxbqdgWiTQvA:-L4oDZurx-ZvaqujSG9i:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/main/java/com/vaadin/flow/component/grid/AbstractColumn.java#L111)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Rendering<?> rendering = renderer.render(getElement(), null);
>         rendering.getTemplateElement().get().setAttribute("class", "footer");

This method differs from the method above in `"footer"` attribute value.
Has sense to extract it as a `private` method with additional parameter and delegate.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/grid/Grid.java, line 541 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o-w1hIT7NpYyinbBY:-L4oD_gE79Ntx_tI63eQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/main/java/com/vaadin/flow/component/grid/Grid.java#L541)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Rendering<?> rendering = renderer.render(getElement(), null);
>             rendering.getTemplateElement().get().setAttribute("class",
>                     "header");

Why not call `super.setHeader`  instead ?
OK, you need `rendering` instance here.

Then I would suggest to extract original method to another which returns `Rendering` and delegate in the super class to it (if needed at all).
And call this method here as well.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 590 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o0ulkofn5RZvvwBIL:-L4oFGK2NLEPXP6XJkVD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L590)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> assertCellContent(
>                 "<flow-grid-component-renderer appid=\"ROOT\"><div><label>$$$</label></div></flow-grid-component-renderer>",
>                 cells.get(4));

I strongly object from such exact string comparison.
There are two many hardcoded strings.
It's totally fine if the String content is different. You don't need the exact match. You need only the top level element with the given tag name, _SOME_ attribute values and _SOME_ inner subelements.

I've had hard time once to fixing such comparison because changes in Grid web component (and my PR had no any relation to the test which I have been fixing).
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 599 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4o1rzaz02ZEnucThyS:-L4oFHSfwZr6k3WC0Nrp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/b8e637d9e0de2aed36090b28f0197b59c532e1d2/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L599)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> assertCellContent(
>                 "<flow-grid-component-renderer appid=\"ROOT\"><div><label>$</label></div></flow-grid-component-renderer>",
>                 cells.get(10));

Same here.
Please no exact HTML content matches.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java, line 602 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84#-L4oIyXhOkKWuE_IJJjX:-L4oIyXhOkKWuE_IJJjY:b76h4ar) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/2e833aa360912e55af7c8111804781b94ddc41b4/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java#L602)):*
> private void assertRendereredContent(String expected, WebElement cell) {
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         Assert.assertThat(cell.getAttribute("innerHTML"), CoreMatchers.allOf(
>                 CoreMatchers.startsWith("<flow-grid-component-renderer"),
>                 CoreMatchers.containsString(expected),
>                 CoreMatchers.endsWith("</flow-grid-component-renderer>")));
>     }
</details>

That's OK.
But for your information: I've used JSoup to parse HTML structure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/84)*

**Pull request merged**
