### PR TITLE
Implement user-defined keys for columns

### PR DESCRIPTION
**Pull request by pekam**
Added API for setting a key identifier for a column. This value can be used to retrieve the column later with `Grid::getColumnByKey`.

There's now a clear separation between column ids, that are used only in the internal implementation, and column keys, which are defined and used by users. All public API for using column-ids is removed, and all mentions of the internal id are now using the correct term "id" instead of "key".

Also, `parentColumns` is renamed to `topLevelColumns` to avoid confusion. The getter now initializes it to avoid having column-references in multiple data structures. It's also now private, because it doesn't seem very useful as a public method.

Also, improved javadocs of `Grid::getColumns` to mention that the order may be incorrect when user-reordering is enabled.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid-flow/27)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 391 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-KzxfcRenopxNHHhR0to:-KzxfcRenopxNHHhR0tp:b7sc202) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/92ec7b6b635bb8075d8a38c4cf3ac17dae2078db/src/main/java/com/vaadin/ui/grid/Grid.java#L391)):*
> protected String getColumnId()

Could this be private? If not, it needs to have javadocs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by pekam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 391 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-KzxfcRenopxNHHhR0to:-Kzxjf23BPg3XURCcenn:bdvknql) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/92ec7b6b635bb8075d8a38c4cf3ac17dae2078db/src/main/java/com/vaadin/ui/grid/Grid.java#L391)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> protected String getColumnId()

Could this be private? If not, it needs to have javadocs.
</blockquote></details>

Actually that's not even needed anywhere anymore so I removed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by pekam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0TgJJDBqwou2yYhaF:-L-0TgJJDBqwou2yYhaG:b7zybiz) (no related file):*
I just realized that I made a mistake with the `initTopLevelColumns`. After initializing, it's updated only in `mergeColumns` and not for example when adding columns. So I'll either revert the changes or make it so that the `topLevelColumns` is always requested from a getter that initializes it to avoid book-keeping.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by ahie** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 1334 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0Tj40c4nNQunF8USA:-L-0Tj40c4nNQunF8USB:b-wnioq1) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/a253f7499f2ac06b6b98e83d7a55c1fe2ea86d0d/src/main/java/com/vaadin/ui/grid/Grid.java#L1334)):*
> initTopLevelColumns

Should this just be changed to `getTopLevelColumns`? Both methods that use `topLevelColumns` call this init method before doing so.

---

*[src/test/java/com/vaadin/ui/grid/GridView.java, line 486 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0U93IOxm9nr3LR8hd:-L-0U93IOxm9nr3LR8he:b-fpzkt9) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/92ec7b6b635bb8075d8a38c4cf3ac17dae2078db/src/test/java/com/vaadin/ui/grid/GridView.java#L486)):*
>  grid.getColumnByKey("age").setResizable(true);

Could add a comment that mentions this API before demonstrating its usage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by pekam** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 1334 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0Tj40c4nNQunF8USA:-L-0Z47uNh7mgD6_xBWx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/a253f7499f2ac06b6b98e83d7a55c1fe2ea86d0d/src/main/java/com/vaadin/ui/grid/Grid.java#L1334)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

> initTopLevelColumns

Should this just be changed to `getTopLevelColumns`? Both methods that use `topLevelColumns` call this init method before doing so.
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/ui/grid/GridView.java, line 486 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0U93IOxm9nr3LR8hd:-L-0Z4bmnIhjVa2Z8DTn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/92ec7b6b635bb8075d8a38c4cf3ac17dae2078db/src/test/java/com/vaadin/ui/grid/GridView.java#L486)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

>  grid.getColumnByKey("age").setResizable(true);

Could add a comment that mentions this API before demonstrating its usage.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by ahie** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 1319 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0ZdkrLzH4iM2vy7D7:-L-0ZcBgysWeH5_YvhVU:bkes41y) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/452b9e59d8667961d77475ab4ed7f4d9c6d75e37/src/main/java/com/vaadin/ui/grid/Grid.java#L1319)):*
> ```Java
> 
>     /**
>      * Initializes the list of columns and/or column groups that are direct
> ```

Should update javadocs as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by pekam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/ui/grid/Grid.java, line 1319 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27#-L-0ZdkrLzH4iM2vy7D7:-L-0a1k2gfAjjPx_usZN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid-flow/blob/452b9e59d8667961d77475ab4ed7f4d9c6d75e37/src/main/java/com/vaadin/ui/grid/Grid.java#L1319)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Should update javadocs as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Comment by ahie** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid-flow/27)*

**Pull request merged**
